# Generated by Django 4.2 on 2024-03-16 16:30

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_upload_path),
        ),
    ]
