# Generated by Django 4.2 on 2024-03-16 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
